In [1]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

In [2]:

x = torch.tensor([[1,2,3], [4,5,6]], device=device, dtype=torch.float32)
x.shape, x.device, x.requires_grad


(torch.Size([2, 3]), device(type='cuda', index=0), False)

In [3]:
torch.empty(size=(3,3))

tensor([[-9.7760e+20,  3.0925e-41,  0.0000e+00],
        [ 0.0000e+00,  5.5757e-02,  1.8728e+31],
        [ 5.9571e-02,  7.0374e+22,  0.0000e+00]])

In [4]:
torch.zeros(size=(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
x = torch.rand((3,3))
x

tensor([[0.0790, 0.5505, 0.2175],
        [0.9483, 0.2331, 0.4271],
        [0.3866, 0.4832, 0.8113]])

In [6]:
x.mean(axis=1)

tensor([0.2823, 0.5362, 0.5603])

In [7]:
x.mean(axis=0)

tensor([0.4713, 0.4222, 0.4853])

In [8]:
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [10]:
torch.arange(start=0,end=5, step=1)

tensor([0, 1, 2, 3, 4])

In [11]:
torch.linspace(start=0, end=5, steps=5)

tensor([0.0000, 1.2500, 2.5000, 3.7500, 5.0000])

In [12]:
torch.empty(size=(1,5))

tensor([[-9.8138e+20,  3.0925e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [13]:
torch.empty(size=(1,5)).normal_(mean=0,std=1)

tensor([[-0.4402, -0.1211, -0.2515, -1.5909, -1.3156]])

In [14]:
torch.empty(size=(1,5)).uniform_(0,1)

tensor([[0.0279, 0.0198, 0.2717, 0.8761, 0.7335]])

In [20]:
torch.diag(torch.tensor([1,2,3,4]))

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])

In [21]:
torch.diag(torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]))

tensor([1, 5, 9])

In [22]:
torch.diag(torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]))

tensor([ 1,  6, 11])

In [24]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [25]:
tensor.bool()

tensor([False,  True,  True,  True])

In [26]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [27]:
tensor.long()

tensor([0, 1, 2, 3])

In [29]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [32]:
tensor.float(), tensor.float().dtype

(tensor([0., 1., 2., 3.]), torch.float32)

In [31]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)