In [1]:
import torch
from numpy.conftest import dtype

In [3]:
x = torch.arange(start=0, end=250).reshape(10,25)
x, x.shape

(tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
           14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
           39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
           64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
           89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
          114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124],
         [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
          139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
          164, 165, 166, 167, 168, 169, 170,

In [4]:
x[0], x[0].shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24]),
 torch.Size([25]))

In [5]:
x[:, 0], x[:, 0].shape

(tensor([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225]), torch.Size([10]))

In [7]:
x[2, 0:10], x[2, 0:10].shape

(tensor([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]), torch.Size([10]))

In [9]:
x[0,0] = 100
x

tensor([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
          39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
          64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
          89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
         114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
         139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
         164, 165, 166, 167, 168, 169, 170, 171, 172, 173

In [11]:
a = torch.arange(start=0, end=20)
indices = [0,2,4]
a[indices]

tensor([0, 2, 4])

In [13]:
nrows = [0,2]
ncols = [0, 10]
x[nrows, ncols], x[nrows, ncols].shape

(tensor([100,  60]), torch.Size([2]))

In [15]:
x[nrows], x[nrows].shape

(tensor([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
           14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
           64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74]]),
 torch.Size([2, 25]))

In [19]:
x[(x<5) | (x>10)], x[(x<5) | (x>10)].shape

(tensor([100,   1,   2,   3,   4,  11,  12,  13,  14,  15,  16,  17,  18,  19,
          20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
          34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
          62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
          76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
          90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
         104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
         118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
         132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
         146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
         160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173,
         174, 175, 176, 177, 178, 179, 180, 181, 182

In [23]:
x[x % 2 == 0]

tensor([100,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110,
        112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138,
        140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166,
        168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194,
        196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222,
        224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248])

In [22]:
x % 2 == 0

tensor([[ True, False,  True, False,  True, False,  True, False,  True, False,
          True, False,  True, False,  True, False,  True, False,  True, False,
          True, False,  True, False,  True],
        [False,  True, False,  True, False,  True, False,  True, False,  True,
         False,  True, False,  True, False,  True, False,  True, False,  True,
         False,  True, False,  True, False],
        [ True, False,  True, False,  True, False,  True, False,  True, False,
          True, False,  True, False,  True, False,  True, False,  True, False,
          True, False,  True, False,  True],
        [False,  True, False,  True, False,  True, False,  True, False,  True,
         False,  True, False,  True, False,  True, False,  True, False,  True,
         False,  True, False,  True, False],
        [ True, False,  True, False,  True, False,  True, False,  True, False,
          True, False,  True, False,  True, False,  True, False,  True, False,
          True, False,  True, 

In [25]:
x[x.remainder(2) == 1]

tensor([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,
         29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,  55,
         57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,  81,  83,
         85,  87,  89,  91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111,
        113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139,
        141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
        169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195,
        197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219, 221, 223,
        225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245, 247, 249])

In [26]:
torch.where(x % 2 == 0, -1, x)

tensor([[ -1,   1,  -1,   3,  -1,   5,  -1,   7,  -1,   9,  -1,  11,  -1,  13,
          -1,  15,  -1,  17,  -1,  19,  -1,  21,  -1,  23,  -1],
        [ 25,  -1,  27,  -1,  29,  -1,  31,  -1,  33,  -1,  35,  -1,  37,  -1,
          39,  -1,  41,  -1,  43,  -1,  45,  -1,  47,  -1,  49],
        [ -1,  51,  -1,  53,  -1,  55,  -1,  57,  -1,  59,  -1,  61,  -1,  63,
          -1,  65,  -1,  67,  -1,  69,  -1,  71,  -1,  73,  -1],
        [ 75,  -1,  77,  -1,  79,  -1,  81,  -1,  83,  -1,  85,  -1,  87,  -1,
          89,  -1,  91,  -1,  93,  -1,  95,  -1,  97,  -1,  99],
        [ -1, 101,  -1, 103,  -1, 105,  -1, 107,  -1, 109,  -1, 111,  -1, 113,
          -1, 115,  -1, 117,  -1, 119,  -1, 121,  -1, 123,  -1],
        [125,  -1, 127,  -1, 129,  -1, 131,  -1, 133,  -1, 135,  -1, 137,  -1,
         139,  -1, 141,  -1, 143,  -1, 145,  -1, 147,  -1, 149],
        [ -1, 151,  -1, 153,  -1, 155,  -1, 157,  -1, 159,  -1, 161,  -1, 163,
          -1, 165,  -1, 167,  -1, 169,  -1, 171,  -1, 173

In [28]:
x = torch.tensor([0,1,1,2,3,3,4,4,5])
x.unique()

tensor([0, 1, 2, 3, 4, 5])

In [29]:
x.ndimension()

1

In [30]:
x.numel()

9

In [31]:
x = torch.rand(5,6,7,8)

In [32]:
x.numel()

1680

In [39]:
x = torch.arange(12)
x, x.shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), torch.Size([12]))

In [45]:
y = x.reshape(3,4)
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [46]:
x.stride()

(1,)

In [47]:
y.stride()

(4, 1)

In [48]:
y = y.t()
y

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [50]:
y.stride()

(1, 4)

In [60]:
xx = torch.arange(12).reshape(4,3)


In [61]:
xx. view(-1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
xx.t_()

tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])

In [64]:
xx.contiguous().view(-1)

tensor([ 0,  3,  6,  9,  1,  4,  7, 10,  2,  5,  8, 11])

In [57]:
xx.reshape(-1)

tensor([ 0,  3,  6,  9,  1,  4,  7, 10,  2,  5,  8, 11])

In [71]:
from PIL import Image
import numpy as np

img = Image.open("img.png")
img_np = np.array(img)
img_np.shape

(1281, 720, 4)

In [72]:
img_np = img_np.reshape(4,1281,720)

In [73]:
img_np = img_np.reshape(1708,720,3)


In [74]:
Image.fromarray(img_np).show()

In [78]:
from PIL import Image
import numpy as np

img = Image.open("img_1.png").resize((1024,768))
img_np = np.array(img)
img_np.shape

(768, 1024, 4)

In [79]:
img_np = img_np.reshape((1024, 1024, 3))

In [80]:
img_np.shape

(1024, 1024, 3)

In [81]:
Image.fromarray(img_np).show()

In [82]:
from PIL import Image
import numpy as np

img = Image.open("img_1.png").convert('RGB')
img_np = np.array(img)
img_np.shape

(1066, 800, 3)

In [86]:
img_np = img_np.reshape((533, 1200, 4))

In [89]:
Image.fromarray(img_np).convert('RGB').show()

In [115]:
x = np.random.logseries(1024,1024,3)
x = (x * 255).astype(np.uint8)

TypeError: logseries() takes at most 2 positional arguments (3 given)

In [117]:
x = torch.rand(1024,1024,3)

In [118]:
x.stride()

(3072, 3, 1)

In [120]:
y = x.permute(2,0,1)
y.stride()

(1, 3072, 3)