In [1]:
import torch
device = "cuda" if torch.cuda.is_available() else "mps"

In [2]:

x = torch.tensor([[1,2,3], [4,5,6]], device=device, dtype=torch.float32)
x.shape, x.device, x.requires_grad


(torch.Size([2, 3]), device(type='mps', index=0), False)

In [3]:
torch.empty(size=(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.zeros(size=(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
x = torch.rand((3,3))
x

tensor([[0.8005, 0.2119, 0.6767],
        [0.7302, 0.1507, 0.7388],
        [0.1045, 0.3609, 0.8642]])

In [6]:
x.mean(axis=1)

tensor([0.5630, 0.5399, 0.4432])

In [7]:
x.mean(axis=0)

tensor([0.5451, 0.2412, 0.7599])

In [8]:
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [10]:
torch.arange(start=0,end=5, step=1)

tensor([0, 1, 2, 3, 4])

In [11]:
torch.linspace(start=0, end=5, steps=5)

tensor([0.0000, 1.2500, 2.5000, 3.7500, 5.0000])

In [12]:
torch.empty(size=(1,5))

tensor([[0., 0., 0., 0., 0.]])

In [13]:
torch.empty(size=(1,5)).normal_(mean=0,std=1)

tensor([[-0.6892,  0.1145, -1.9481, -0.6708, -0.8647]])

In [14]:
torch.empty(size=(1,5)).uniform_(0,1)

tensor([[0.7683, 0.9391, 0.4827, 0.8930, 0.7417]])

In [15]:
torch.diag(torch.tensor([1,2,3,4]))

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])

In [16]:
torch.diag(torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]))

tensor([1, 5, 9])

In [17]:
torch.diag(torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]))

tensor([ 1,  6, 11])

In [18]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [19]:
tensor.bool()

tensor([False,  True,  True,  True])

In [20]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [21]:
tensor.long()

tensor([0, 1, 2, 3])

In [22]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [23]:
tensor.float(), tensor.float().dtype

(tensor([0., 1., 2., 3.]), torch.float32)

In [24]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [25]:
import numpy as np
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [26]:
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])