In [1]:
import torch
from numpy.ma.core import indices

In [2]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [3]:
z = x + y
z

tensor([10, 10, 10])

In [4]:
z = x - y
z

tensor([-8, -6, -4])

In [5]:
z = x/y
z

tensor([0.1111, 0.2500, 0.4286])

In [6]:
z = torch.true_divide(x, y)
z

tensor([0.1111, 0.2500, 0.4286])

In [7]:
y1 = torch.tensor([0,1,2])
x/y1, torch.true_divide(x,y1)

(tensor([   inf, 2.0000, 1.5000]), tensor([   inf, 2.0000, 1.5000]))

In [8]:
x = torch.tensor([1,2,3])
x.pow(2)

tensor([1, 4, 9])

In [9]:
y = torch.tensor([1,2,3])
x.pow(y)

tensor([ 1,  4, 27])

In [10]:
x = torch.tensor([0,2,4,-4,3])
x > 0

tensor([False,  True,  True, False,  True])

In [11]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1, x2)
x3, x3.shape

(tensor([[0.8122, 1.4531, 0.8314],
         [1.3572, 1.0322, 1.2726]]),
 torch.Size([2, 3]))

In [12]:
x1 = torch.arange(start=1, end=10)
x1 = x1.reshape((3,3))
x1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
x1.pow(y)

tensor([[  1,   4,  27],
        [  4,  25, 216],
        [  7,  64, 729]])

In [14]:
y

tensor([1, 2, 3])

In [18]:
matrix_exp = torch.arange(start=1, end=10).reshape((3,3))
matrix_exp

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
matrix_exp.matrix_power(2)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

tensor([[ 468,  576,  684],
        [1062, 1305, 1548],
        [1656, 2034, 2412]])

In [23]:
matrix_exp * matrix_exp

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [28]:
x = torch.arange(start=0, end=25).reshape((5,5))
x, x.shape

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]]),
 torch.Size([5, 5]))

In [31]:
y = torch.arange(start=0, end=5)
y = y.unsqueeze_(dim=0)
y, y.shape

(tensor([[0, 1, 2, 3, 4]]), torch.Size([1, 5]))

In [33]:
x+y, x-y

(tensor([[ 0,  2,  4,  6,  8],
         [ 5,  7,  9, 11, 13],
         [10, 12, 14, 16, 18],
         [15, 17, 19, 21, 23],
         [20, 22, 24, 26, 28]]),
 tensor([[ 0,  0,  0,  0,  0],
         [ 5,  5,  5,  5,  5],
         [10, 10, 10, 10, 10],
         [15, 15, 15, 15, 15],
         [20, 20, 20, 20, 20]]))

In [35]:
torch.max(x)

(tensor(24),
 torch.return_types.max(
 values=tensor([20, 21, 22, 23, 24]),
 indices=tensor([4, 4, 4, 4, 4])))

In [36]:
values, indices = torch.max(x, dim=0)
values, indices

(tensor([20, 21, 22, 23, 24]), tensor([4, 4, 4, 4, 4]))

In [37]:
values, indices = torch.min(x, dim=1)

In [38]:
values, indices

(tensor([ 0,  5, 10, 15, 20]), tensor([0, 0, 0, 0, 0]))

In [41]:
mean_x = torch.mean(x.double())
mean_x

tensor(12., dtype=torch.float64)

In [45]:
torch.mean(x.float())

tensor(12.)

In [47]:
torch.mean(x.float(), dim=0), torch.mean(x.float(), dim=1)

(tensor([10., 11., 12., 13., 14.]), tensor([ 2.,  7., 12., 17., 22.]))

In [48]:
torch.eq(x, y)

tensor([[ True,  True,  True,  True,  True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [51]:
torch.sort(x, descending=True)

torch.return_types.sort(
values=tensor([[ 4,  3,  2,  1,  0],
        [ 9,  8,  7,  6,  5],
        [14, 13, 12, 11, 10],
        [19, 18, 17, 16, 15],
        [24, 23, 22, 21, 20]]),
indices=tensor([[4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0],
        [4, 3, 2, 1, 0]]))

In [52]:
y

tensor([[0, 1, 2, 3, 4]])

In [56]:
x = torch.arange(start=0, end=25)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

In [60]:
x_clamp = x.clamp(min=4)
x_clamp

tensor([ 4,  4,  4,  4,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

In [61]:
x_clamp = x.clamp(max=10)
x_clamp

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10])

In [62]:
x.clamp(min=4, max=10)

tensor([ 4,  4,  4,  4,  4,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10])

In [63]:
x = torch.tensor([0,2,3,1,0,3], dtype=torch.bool)
x

tensor([False,  True,  True,  True, False,  True])

In [64]:
torch.any(x)

tensor(True)

In [65]:
torch.all(x)

tensor(False)

In [68]:
batch = 100
m = 10
n = 20
p = 30

x = torch.rand(batch,m,n)
y = torch.rand(batch, n, p)

In [70]:
z = torch.bmm(x, y)
z.shape

torch.Size([100, 10, 30])